/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

@class PSRootController, PSSpecifier;

@interface PSViewController : UIViewController
{
    UIViewController *_parentController;
    PSRootController *_rootController;
    PSSpecifier *_specifier;
}

- (id)init;
- (void)setParentController:(id)arg1;
- (id)parentController;
- (void)setRootController:(id)arg1;
- (id)rootController;
- (void)dealloc;
- (void)setSpecifier:(id)arg1;
- (id)specifier;
- (void)setPreferenceValue:(id)arg1 specifier:(id)arg2;
- (id)readPreferenceValue:(id)arg1;
- (void)willResignActive;
- (void)willBecomeActive;
- (void)suspend;
- (void)didLock;
- (void)willUnlock;
- (void)didUnlock;
- (void)didWake;
- (void)pushController:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)arg1;
- (void)handleURL:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)popupViewWillDisappear;
- (void)popupViewDidDisappear;
- (void)formSheetViewWillDisappear;
- (void)formSheetViewDidDisappear;
- (BOOL)canBeShownFromSuspendedState;
- (void)statusBarWillAnimateByHeight:(float)arg1;

@end

